spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "update"

firebase:
  admin:
    credentials:
      path: ".secrets/firebase-admin-sdk.json"

orka:
  guest:
    session-ttl: "PT1H"
